GET http://localhost:8080/api/persons/

###
POST http://localhost:8080/api/persons/ HTTP/1.1
content-type: application/json

{
      "name": " amoverb",
      "number": "124-234345788",
      "userId": "639cd59b30ae8ff8593301da"
}

###
GET http://localhost:8080/api/users/


###
POST http://localhost:8080/api/users/ HTTP/1.1
content-type: application/json

{
    "username": "root",
    "name": "Superuser",
    "password": "salainen"
}

###
POST http://localhost:8080/api/login/ HTTP/1.1
content-type: application/json

{
    "username": "root",
    "password": "salainen"
}
